### ISSUE TITLE
Giving ownership to someone else?

### ISSUE THREAD

**Issue by Aur0nd** [minicloudlabs/helm-charts#107]
Unfortunately there's a few PRs pending and there's no one to review them.

I'd be more than happy to take over if there's no one else to run the repo - hopefully we won't have to fork this one and create a new one.

**Comment by 8ball030** [comment]
I have to say it normally seems as though this repo is well maintained.

Would be cool to get some of these prs merged but seems quite excessive to push the maintainer to give up ownership based on some put standing prs.

**Comment by 8ball030** [comment]
> So you're suggesting it'd be better to fork or just redo the work in another repo instead of carry on using this one?

I'm saying that I think the maintainer is still around, and that I think your being pushy to get some small fix in. 

If you want to fork, go ahead, noones gonna stop you. If anything, personally I'd rather people did fork stuff rather than try to pressure owners into handing over repos to untested quantities.

**Comment by avakarev** [comment]
Heya, sorry for being unresponsive last few months.

Because of personal/family reasons I can't afford to spend time on this repo.  I would be totally happy to archive the repo and put a bold note in readme with a new location. Or even transfer the repo, whatever fits best.

Github says there was 87k+ downloads for latest chart release, so it make sense to move repo to better place.

```sh
curl -s https://api.github.com/repos/minicloudlabs/helm-charts/releases/158254307 | jq '.assets[0].download_count'
87792
```

@TwiN please, let me know if you have any interest to take it over.

**Comment by TwiN** [comment]
@avakarev Hey, no worries.

If you're willing, you could make a PR for TwiN/helm-charts that overwrites my (very simple) gatus chart - just perhaps leave the current Chart.yaml and bump the version by a major version. I'll take care of the rest when I have some time. Make sure to allow edits from the maintainer, as I'll probably modify your PR directly.

If you'd like, you can also leave your username somewhere in the repo for credit.

That said, I sincerely appreciate the work you've done for Gatus and I wish you luck with your personal/family circumstances.

**Comment by avakarev** [comment]
@TwiN Heya, fantastic. There is a "common lib" chart dependency. So, before releasing new gatus chart, initial common-lib chart must be released. This is how it's structured now. Alternatively, [common-lib](https://github.com/minicloudlabs/helm-charts/tree/main/charts/common/templates) could also be replaced by [bitnami's common-lib](https://artifacthub.io/packages/helm/bitnami/common) or it could just be embedded into the gatus chart.

So, if you want to keep the structure, I can send 2 prs for `TwiN/helm-charts`:
  - common-lib, version 1.0.0 (must be released after/on merge)
  - new gatus chart templates with no changes in `Chart.yaml`, dependent on common-lib
  
Please, let me know whatever works better.

**Comment by TwiN** [comment]
@avakarev just because I don't trust companies to do _The Right Thing™️_ for the open source world, I'd rather go the embedded route - if their license permits it.

As for everything else, do whatever's easier for you. You mentioned personal/family circumstances; please prioritize them. Life is short. Do whatever is easiest for you, whenever you have time to spare, and I will take care of everything else.

**Comment by avakarev** [comment]
@Aur0nd @8ball030 Just a quick heads-up that the this repository is no longer maintained.

Please, read gatus chart migration notes: https://github.com/minicloudlabs/helm-charts/tree/main/charts/gatus
